In [1]:
import pandas as pd

In [72]:
df = pd.read_excel(r"C:/Users/Aditya/Downloads/Pizza/Enhanced_pizza_sell_data_2024-25.xlsx")

In [73]:
df

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
1,ORD002,Papa John's,"Los Angeles, CA",2024-02-14 20:00:00,2024-02-14 20:25:00,25,Large,Non-Veg,4,5.0,...,0.800000,February,Online,12.0,13.0,False,12,3,20,28.186275
2,ORD003,Little Caesars,"Chicago, IL",2024-03-21 12:15:00,2024-03-21 12:35:00,20,Small,Vegan,2,3.0,...,0.666667,March,Online,7.2,12.8,False,2,1,12,28.844221
3,ORD004,Pizza Hut,"Miami, FL",2024-04-10 19:45:00,2024-04-10 20:10:00,25,XL,Cheese Burst,5,4.5,...,1.111111,April,Offline,10.8,14.2,False,20,2,19,29.948454
4,ORD005,Marco's Pizza,"Dallas, TX",2024-05-05 13:00:00,2024-05-05 13:20:00,20,Medium,Non-Veg,3,2.0,...,1.500000,May,Online,4.8,15.2,False,6,3,13,30.286458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,ORD1001,Domino's,"Albuquerque, NM",2026-07-03 19:00:00,2026-07-03 19:30:00,30,Large,Sicilian,4,5.5,...,0.727273,July,Online,13.2,16.8,False,12,2,19,30.259434
1000,ORD1002,Pizza Hut,"Atlanta, GA",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,July,Online,9.6,20.4,False,4,1,20,29.948454
1001,ORD1003,Papa John's,"Omaha, NE",2026-07-05 18:30:00,2026-07-05 19:00:00,30,Medium,BBQ Chicken,3,5.0,...,0.600000,July,Online,12.0,18.0,False,6,2,18,28.186275
1002,ORD1004,Little Caesars,"Louisville, KY",2026-07-06 19:45:00,2026-07-06 20:15:00,30,XL,Cheese Burst,5,6.0,...,0.833333,July,Online,14.4,15.6,False,20,3,19,28.844221
1003,ORD1005,Marco's Pizza,"Milwaukee, WI",2026-07-07 20:00:00,2026-07-07 20:30:00,30,Medium,Margarita,3,4.5,...,0.666667,July,Online,10.8,19.2,False,6,2,20,30.286458

In [17]:
# 1. Dataset ki first 5 rows display karo.
df.head()

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
1,ORD002,Papa John's,"Los Angeles, CA",2024-02-14 20:00:00,2024-02-14 20:25:00,25,Large,Non-Veg,4,5.0,...,0.800000,February,Online,12.0,13.0,False,12,3,20,28.186275
2,ORD003,Little Caesars,"Chicago, IL",2024-03-21 12:15:00,2024-03-21 12:35:00,20,Small,Vegan,2,3.0,...,0.666667,March,Online,7.2,12.8,False,2,1,12,28.844221
3,ORD004,Pizza Hut,"Miami, FL",2024-04-10 19:45:00,2024-04-10 20:10:00,25,XL,Cheese Burst,5,4.5,...,1.111111,April,Offline,10.8,14.2,False,20,2,19,29.948454
4,ORD005,Marco's Pizza,"Dallas, TX",2024-05-05 13:00:00,2024-05-05 13:20:00,20,Medium,Non-Veg,3,2.0,...,1.500000,May,Online,4.8,15.2,False,6,3,13,30.286458

In [6]:
# 2. Dataset me total rows aur columns count karo.
df.shape

(1004, 25)

In [18]:
# 3. Dataset ke sabhi column names print karo.
df.columns

Index(['Order ID', 'Restaurant Name', 'Location', 'Order Time',
       'Delivery Time', 'Delivery Duration (min)', 'Pizza Size', 'Pizza Type',
       'Toppings Count', 'Distance (km)', 'Traffic Level', 'Payment Method',
       'Is Peak Hour', 'Is Weekend', 'Delivery Efficiency (min/km)',
       'Topping Density', 'Order Month', 'Payment Category',
       'Estimated Duration (min)', 'Delay (min)', 'Is Delayed',
       'Pizza Complexity', 'Traffic Impact', 'Order Hour',
       'Restaurant Avg Time'],
      dtype='str')

In [8]:
# 4. Dataset ki basic information (`info()`) nikalo.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Order ID                      1004 non-null   str
 1   Restaurant Name               1004 non-null   str
 2   Location                      1004 non-null   str
 3   Order Time                    1004 non-null   datetime64[us]
 4   Delivery Time                 1004 non-null   datetime64[us]
 5   Delivery Duration (min)       1004 non-null   int64
 6   Pizza Size                    1004 non-null   str
 7   Pizza Type                    1004 non-null   str
 8   Toppings Count                1004 non-null   int64
 9   Distance (km)                 1004 non-null   float64
 10  Traffic Level                 1004 non-null   str
 11  Payment Method                1004 non-null   str
 12  Is Peak Hour                  1004 non-null   bool
 13  Is Weekend                    1004 non-null   bool
 14  Delivery Efficiency (min/km)  1004 non-null   float64
 15  Topping Density               1004 non-null   float64
 16  Order Month                   1004 non-null   str
 17  Payment Category              1004 non-null   str
 18  Estimated Duration (min)      1004 non-null   float64
 19  Delay (min)                   1004 non-null   float64
 20  Is Delayed                    1004 non-null   bool
 21  Pizza Complexity              1004 non-null   int64
 22  Traffic Impact                1004 non-null   int64
 23  Order Hour                    1004 non-null   int64
 24  Restaurant Avg Time           1004 non-null   float64
dtypes: bool(3), datetime64[us](2), float64(6), int64(5), str(9)
memory usage: 175.6 KB

In [9]:
# 5. Dataset me null values check karo.
df.isnull().sum()

Order ID                        0
Restaurant Name                 0
Location                        0
Order Time                      0
Delivery Time                   0
Delivery Duration (min)         0
Pizza Size                      0
Pizza Type                      0
Toppings Count                  0
Distance (km)                   0
Traffic Level                   0
Payment Method                  0
Is Peak Hour                    0
Is Weekend                      0
Delivery Efficiency (min/km)    0
Topping Density                 0
Order Month                     0
Payment Category                0
Estimated Duration (min)        0
Delay (min)                     0
Is Delayed                      0
Pizza Complexity                0
Traffic Impact                  0
Order Hour                      0
Restaurant Avg Time             0
dtype: int64

In [10]:
# 6. Dataset me total orders count karo.
df = df.shape[0]

("Total Orders:", df)

('Total Orders:', 1004)

In [26]:
# 7. Sabse zyada Delivery Duration wala order find karo.
df= df[df['Delivery Duration (min)'] == df['Delivery Duration (min)'].max()]

In [27]:
df

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
129,ORD130,Marco's Pizza,"Phoenix, AZ",2024-08-05 19:00:00,2024-08-05 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,August,Online,24.00,26.00,True,12,3,19,30.286458
139,ORD140,Marco's Pizza,"Fort Worth, TX",2024-08-15 19:00:00,2024-08-15 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,August,Online,24.00,26.00,True,12,3,19,30.286458
149,ORD150,Marco's Pizza,"Boston, MA",2024-08-25 19:00:00,2024-08-25 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,August,Online,24.00,26.00,True,12,3,19,30.286458
270,ORD271,Marco's Pizza,"Miami, FL",2024-09-14 19:00:00,2024-09-14 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,September,Offline,24.00,26.00,True,12,3,19,30.286458
309,ORD311,Marco's Pizza,"Phoenix, AZ",2024-08-30 19:00:00,2024-08-30 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,August,Online,24.00,26.00,True,12,3,19,30.286458
319,ORD321,Marco's Pizza,"Fort Worth, TX",2024-09-09 19:00:00,2024-09-09 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,September,Online,24.00,26.00,True,12,3,19,30.286458
329,ORD331,Marco's Pizza,"Boston, MA",2024-09-19 19:00:00,2024-09-19 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,September,Online,24.00,26.00,True,12,3,19,30.286458
334,ORD336,Marco's Pizza,"Phoenix, AZ",2024-09-24 19:00:00,2024-09-24 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,September,Online,24.00,26.00,True,12,3,19,30.286458
339,ORD341,Marco's Pizza,"Phoenix, AZ",2024-09-29 19:00:00,2024-09-29 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,September,Online,24.00,26.00,True,12,3,19,30.286458
349,ORD351,Marco's Pizza,"Fort Worth, TX",2024-10-09 19:00:00,2024-10-09 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,October,Online,24.00,26.00,True,12,3,19,30.286458
359,ORD361,Marco's Pizza,"Boston, MA",2024-10-19 19:00:00,2024-10-19 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,October,Online,24.00,26.00,True,12,3,19,30.286458
365,ORD367,Marco's Pizza,"Phoenix, AZ",2024-10-25 19:00:00,2024-10-25 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,October,Online,24.00,26.00,True,12,3,19,30.286458
375,ORD377,Marco's Pizza,"Fort Worth, TX",2024-11-04 19:00:00,2024-11-04 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.00,26.00,True,12,3,19,30.286458
385,ORD387,Marco's Pizza,"Boston, MA",2024-11-14 19:00:00,2024-11-14 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.00,26.00,True,12,3,19,30.286458
391,ORD393,Marco's Pizza,"Phoenix, AZ",2024-11-20 19:00:00,2024-11-20 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.00,26.00,True,12,3,19,30.286458
401,ORD403,Marco's Pizza,"Fort Worth, TX",2024-11-30 19:00:00,2024-11-30 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.00,26.00,True,12,3,19,30.286458
411,ORD413,Marco's Pizza,"Boston, MA",2024-12-10 19:00:00,2024-12-10 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,December,Online,24.00,26.00,True,12,3,19,30.286458
417,ORD419,Marco's Pizza,"Phoenix, AZ",2024-12-16 19:00:00,2024-12-16 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,December,Online,24.00,26.00,True,12,3,19,30.286458
427,ORD429,Marco's Pizza,"Phoenix, AZ",2024-12-16 19:00:00,2024-12-16 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,December,Online,24.00,26.00,True,12,3,19,30.286458
437,ORD439,Marco's Pizza,"Fort Worth, TX",2024-12-26 19:00:00,2024-12-26 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,December,Online,24.00,26.00,True,12,3,19,30.286458
447,ORD449,Marco's Pizza,"Boston, MA",2025-01-05 19:00:00,2025-01-05 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,January,Online,24.00,26.00,True,12,3,19,30.286458
455,ORD457,Pizza Hut,"Seattle, WA",2025-01-13 19:00:00,2025-01-13 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,January,Online,24.00,26.00,True,12,3,19,29.948454
463,ORD465,Domino's,"Phoenix, AZ",2025-01-21 19:00:00,2025-01-21 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,January,Online,24.00,26.00,True,12,3,19,30.259434
473,ORD475,Domino's,"Charlotte, NC",2025-01-31 19:00:00,2025-01-31 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,January,Online,24.00,26.00,True,12,3,19,30.259434
483,ORD485,Domino's,"Milwaukee, WI",2025-02-10 19:00:00,2025-02-10 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,February,Online,24.00,26.00,True,12,3,19,30.259434
491,ORD493,Domino's,"Atlanta, GA",2025-02-18 19:00:00,2025-02-18 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,February,Online,24.00,26.00,True,12,3,19,30.259434
501,ORD503,Domino's,"Tampa, FL",2025-02-28 19:00:00,2025-02-28 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,February,Offline,24.00,26.00,True,12,3,19,30.259434
511,ORD513,Domino's,"Newark, NJ",2025-03-10 19:00:00,2025-03-10 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,March,Online,24.00,26.00,True,12,3,19,30.259434
519,ORD521,Domino's,"Orlando, FL",2025-03-18 19:00:00,2025-03-18 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,March,Online,24.00,26.00,True,12,3,19,30.259434
529,ORD531,Domino's,"Fort Wayne, IN",2025-03-28 19:00:00,2025-03-28 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,March,Offline,24.00,26.00,True,12,3,19,30.259434
539,ORD541,Domino's,"Akron, OH",2025-04-07 19:00:00,2025-04-07 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,April,Online,24.00,26.00,True,12,3,19,30.259434
552,ORD554,Domino's,"Columbus, OH",2025-04-20 19:00:00,2025-04-20 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,April,Offline,24.00,26.00,True,12,3,19,30.259434
562,ORD564,Domino's,"Baltimore, MD",2025-04-30 19:00:00,2025-04-30 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,April,Online,24.00,26.00,True,12,3,19,30.259434
579,ORD581,Domino's,"Austin, TX",2025-05-17 19:00:00,2025-05-17 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,May,Offline,24.00,26.00,True,12,3,19,30.259434
589,ORD591,Domino's,"Boston, MA",2025-05-27 19:00:00,2025-05-27 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,May,Online,24.00,26.00,True,12,3,19,30.259434
609,ORD611,Domino's,"Austin, TX",2025-06-16 19:00:00,2025-06-16 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,June,Offline,24.00,26.00,True,12,3,19,30.259434
619,ORD621,Domino's,"Boston, MA",2025-06-26 19:00:00,2025-06-26 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,June,Online,24.00,26.00,True,12,3,19,30.259434
625,ORD627,Little Caesars,"Atlanta, GA",2025-06-15 20:05:00,2025-06-15 20:55:00,50,XL,Non-Veg,5,8.7,...,0.574713,June,Offline,20.88,29.12,True,20,3,20,28.844221
635,ORD637,Papa John's,"San Diego, CA",2025-06-18 17:45:00,2025-06-18 18:35:00,50,Large,Non-Veg,4,8.3,...,0.481928,June,Online,19.92,30.08,True,12,3,17,28.186275
644,ORD646,Domino's,"San Francisco, CA",2025-07-21 19:00:00,2025-07-21 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,July,Online,24.00,26.00,True,12,3,19,30.259434

In [29]:
# 7.
df["Delivery Duration (min)"].max()

np.int64(50)

In [37]:
# 8. Top 5 longest delivery orders display karo.
df.sort_values(by='Delivery Duration (min)',ascending=False).head(5)

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
129,ORD130,Marco's Pizza,"Phoenix, AZ",2024-08-05 19:00:00,2024-08-05 19:50:00,50,Large,Non-Veg,4,10.0,...,0.4,August,Online,24.0,26.0,True,12,3,19,30.286458
139,ORD140,Marco's Pizza,"Fort Worth, TX",2024-08-15 19:00:00,2024-08-15 19:50:00,50,Large,Non-Veg,4,10.0,...,0.4,August,Online,24.0,26.0,True,12,3,19,30.286458
149,ORD150,Marco's Pizza,"Boston, MA",2024-08-25 19:00:00,2024-08-25 19:50:00,50,Large,Non-Veg,4,10.0,...,0.4,August,Online,24.0,26.0,True,12,3,19,30.286458
270,ORD271,Marco's Pizza,"Miami, FL",2024-09-14 19:00:00,2024-09-14 19:50:00,50,Large,Non-Veg,4,10.0,...,0.4,September,Offline,24.0,26.0,True,12,3,19,30.286458
309,ORD311,Marco's Pizza,"Phoenix, AZ",2024-08-30 19:00:00,2024-08-30 19:50:00,50,Large,Non-Veg,4,10.0,...,0.4,August,Online,24.0,26.0,True,12,3,19,30.286458

In [55]:
# 9. Dataset me kitne unique Pizza Types hain, count karo.
df['Pizza Type'].unique()

<StringArray>
[          'Veg',       'Non-Veg',         'Vegan',  'Cheese Burst',
   'Gluten-Free', 'Stuffed Crust',    'Thin Crust',     'Deep Dish',
  'Thai Chicken',      'Sicilian',   'BBQ Chicken',     'Margarita']
Length: 12, dtype: str

In [51]:
# 10. Average Delivery Duration calculate karo.
df['Delivery Duration (min)'].mean()

np.float64(29.49203187250996)

In [57]:
# 11. Har Pizza Type ka total orders count karo.
df['Pizza Type'].value_counts()

Pizza Type
Non-Veg          216
Veg              202
Cheese Burst     188
Vegan            132
Sicilian          64
BBQ Chicken       54
Margarita         54
Gluten-Free       41
Thai Chicken      24
Stuffed Crust     21
Deep Dish          6
Thin Crust         2
Name: count, dtype: int64

In [74]:
# 12. Sabse zyada order hone wala Pizza Type find karo.
df['Pizza Type'].value_counts().idxmax()

'Non-Veg'

In [87]:
# 13. Medium size pizzas ke total orders count karo.
medium = df[df['Pizza Size']== 'Medium'].shape[0]
print('Total_Medium_size pizza',medium)

Total_Medium_size pizza 429

In [88]:
# 14. Large size pizzas ke total orders count karo
Large = df[df['Pizza Size']=='Large'].shape[0]
print('Total_Large_size pizza',Large)

Total_Large_size pizza 240

In [91]:
# 15. Sabse kam Delivery Duration wala order find karo.
df[df['Delivery Duration (min)']==df['Delivery Duration (min)'].min()]

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.2,January,Online,6.0,9.0,False,6,2,18,30.259434

In [94]:
df['Delivery Duration (min)'].min()

np.int64(15)

In [105]:
# 16. Dataset ko Delivery Duration ke according ascending order me sort karo.
df.sort_values(by='Delivery Duration (min)',ascending=True)

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
27,ORD028,Little Caesars,"Boston, MA",2024-01-28 18:30:00,2024-01-28 18:50:00,20,Medium,Non-Veg,3,3.5,...,0.857143,January,Offline,8.4,11.6,False,6,3,18,28.844221
22,ORD023,Little Caesars,"Houston, TX",2024-01-23 19:30:00,2024-01-23 19:50:00,20,Medium,Non-Veg,3,3.5,...,0.857143,January,Online,8.4,11.6,False,6,1,19,28.844221
29,ORD030,Marco's Pizza,"Miami, FL",2024-01-30 13:15:00,2024-01-30 13:35:00,20,Medium,Non-Veg,3,3.0,...,1.000000,January,Online,7.2,12.8,False,6,2,13,30.286458
10,ORD011,Domino's,"San Francisco, CA",2024-01-11 17:30:00,2024-01-11 17:50:00,20,Large,Veg,4,4.0,...,1.000000,January,Online,9.6,10.4,False,12,1,17,30.259434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,ORD387,Marco's Pizza,"Boston, MA",2024-11-14 19:00:00,2024-11-14 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.0,26.0,True,12,3,19,30.286458
391,ORD393,Marco's Pizza,"Phoenix, AZ",2024-11-20 19:00:00,2024-11-20 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.0,26.0,True,12,3,19,30.286458
365,ORD367,Marco's Pizza,"Phoenix, AZ",2024-10-25 19:00:00,2024-10-25 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,October,Online,24.0,26.0,True,12,3,19,30.286458
375,ORD377,Marco's Pizza,"Fort Worth, TX",2024-11-04 19:00:00,2024-11-04 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,November,Online,24.0,26.0,True,12,3,19,30.286458
349,ORD351,Marco's Pizza,"Fort Worth, TX",2024-10-09 19:00:00,2024-10-09 19:50:00,50,Large,Non-Veg,4,10.0,...,0.400000,October,Online,24.0,26.0,True,12,3,19,30.286458

In [106]:
# 17. Sirf Veg pizzas ka data filter karo.
df[df['Pizza Type'] == 'Veg']

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
6,ORD007,Papa John's,"Los Angeles, CA",2024-01-07 20:15:00,2024-01-07 20:40:00,25,Large,Veg,4,4.5,...,0.888889,January,Online,10.8,14.2,False,12,2,20,28.186275
10,ORD011,Domino's,"San Francisco, CA",2024-01-11 17:30:00,2024-01-11 17:50:00,20,Large,Veg,4,4.0,...,1.000000,January,Online,9.6,10.4,False,12,1,17,30.259434
15,ORD016,Domino's,"Denver, CO",2024-01-16 19:45:00,2024-01-16 20:10:00,25,Large,Veg,4,4.5,...,0.888889,January,Offline,10.8,14.2,False,12,3,19,30.259434
20,ORD021,Domino's,"Miami, FL",2024-01-21 18:45:00,2024-01-21 19:10:00,25,Large,Veg,4,4.5,...,0.888889,January,Online,10.8,14.2,False,12,2,18,30.259434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,ORD982,Pizza Hut,"Atlanta, GA",2026-06-14 20:15:00,2026-06-14 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
985,ORD987,Pizza Hut,"Atlanta, GA",2026-06-19 20:30:00,2026-06-19 21:00:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
990,ORD992,Pizza Hut,"Atlanta, GA",2026-06-24 20:15:00,2026-06-24 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
995,ORD997,Pizza Hut,"Atlanta, GA",2026-06-29 20:30:00,2026-06-29 21:00:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
1000,ORD1002,Pizza Hut,"Atlanta, GA",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,July,Online,9.6,20.4,False,4,1,20,29.948454

In [114]:
# 18. Total Distance (km) ka sum calculate karo.
df['Distance (km)'].sum()

np.float64(4965.4)

In [118]:
# 19. Kisi ek specific Pizza Type ka complete data display karo.
df[df['Pizza Type'] == 'Veg']

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Pizza Size,Pizza Type,Toppings Count,Distance (km),...,Topping Density,Order Month,Payment Category,Estimated Duration (min),Delay (min),Is Delayed,Pizza Complexity,Traffic Impact,Order Hour,Restaurant Avg Time
0,ORD001,Domino's,"New York, NY",2024-01-05 18:30:00,2024-01-05 18:45:00,15,Medium,Veg,3,2.5,...,1.200000,January,Online,6.0,9.0,False,6,2,18,30.259434
6,ORD007,Papa John's,"Los Angeles, CA",2024-01-07 20:15:00,2024-01-07 20:40:00,25,Large,Veg,4,4.5,...,0.888889,January,Online,10.8,14.2,False,12,2,20,28.186275
10,ORD011,Domino's,"San Francisco, CA",2024-01-11 17:30:00,2024-01-11 17:50:00,20,Large,Veg,4,4.0,...,1.000000,January,Online,9.6,10.4,False,12,1,17,30.259434
15,ORD016,Domino's,"Denver, CO",2024-01-16 19:45:00,2024-01-16 20:10:00,25,Large,Veg,4,4.5,...,0.888889,January,Offline,10.8,14.2,False,12,3,19,30.259434
20,ORD021,Domino's,"Miami, FL",2024-01-21 18:45:00,2024-01-21 19:10:00,25,Large,Veg,4,4.5,...,0.888889,January,Online,10.8,14.2,False,12,2,18,30.259434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,ORD982,Pizza Hut,"Atlanta, GA",2026-06-14 20:15:00,2026-06-14 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
985,ORD987,Pizza Hut,"Atlanta, GA",2026-06-19 20:30:00,2026-06-19 21:00:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
990,ORD992,Pizza Hut,"Atlanta, GA",2026-06-24 20:15:00,2026-06-24 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
995,ORD997,Pizza Hut,"Atlanta, GA",2026-06-29 20:30:00,2026-06-29 21:00:00,30,Medium,Veg,2,4.0,...,0.500000,June,Online,9.6,20.4,False,4,1,20,29.948454
1000,ORD1002,Pizza Hut,"Atlanta, GA",2026-07-04 20:15:00,2026-07-04 20:45:00,30,Medium,Veg,2,4.0,...,0.500000,July,Online,9.6,20.4,False,4,1,20,29.948454

In [119]:
# 20. Top 3 most ordered pizzas find karo.
df['Pizza Type'].value_counts().head(3)

Pizza Type
Non-Veg         216
Veg             202
Cheese Burst    188
Name: count, dtype: int64